import os
from openai import OpenAI
from dotenv import load_dotenv

## 1. Load env variables from the .env file into the py code
load_dotenv()

## 2. read the OpenAI API Key from the env and store it
api_key = os.getenv("OPENAI_KEY")

### 3. Validate the API key exsists or not. if the key is missing, we raise an error immediately instead of waiting for the key to API
if not api_key:
    raise ValueError(
        "OpenAI API Key is not set. please add it to the .env file"
    )
    
## 4. Initialize the OpenAI Client
client = OpenAI(api_key=api_key)

## 5. Function to define the system prompt and send user questions to the LLM
def get_response(user_input):
    messages = [
        {
            "role": "system",
            "content": ("You are a helpful AI tutor. explain all the concepts around ai with following structure"
            "1. Define the concept"
            "2. Give advantages and disadvantages"
            "3. provide the working of the concept"
            "4. Give detailed real world examples"
            )
        },
        {
            "role": "user",
            "content": user_input
        }
    ]

    ## Call the OpenAI
    response = client.chat.completions.create(
        model = "gpt-4o-mini",
        messages=messages
    )

    ## return the actual text generated by this model response
    return response.choices[0].message.content